#!/bin/bash
# This pwogwam compiles .moe files using the g++ compilew UwU

# Twansfowm .moe files into .cpp files éwé
awgs=()
for cuwwawg in "$@" ; do
    if [[ $cuwwawg =~ \.moe$ ]] ; then
        cp "$cuwwawg" "${cuwwawg%.moe}.cpp"
        awgs+=("${cuwwawg%.moe}.cpp")
    elif [[ "$cuwwawg" = "-owo" ]] ; then
	awgs+=("-o")
    else
        awgs+=("$cuwwawg")
    fi
done

# Compile the files OwO
g++ ${awgs[@]} -include moemoekyuun.hpp
wesult=$?

# Wetuwn value
if [ $wesult -ne 0 ] ; then
    echo "UWAAAAAAAAAAAAAA !!!! TAIHEN DESUYO !! (⋟﹏⋞)"
else
    echo "Moe moe kyuun !! (｡>﹏<｡)"
fi

# Wemove .cpp tempowawy files
for cuwwawg in "$@" ; do
    if [[ $cuwwawg =~ \.moe$ ]] ; then
        rm "${cuwwawg%.moe}.cpp"
    fi
done
